### ISSUE TITLE
Shared libraries

### ISSUE THREAD

**Issue by paucazou** [kerberos-io/documentation#19]
Hi,
thanks for your wonderful project.
I just tried to follow the documentation to install Kerberos on Raspberry Pi OS, and found that some libraries were missing:
libvorbisenc.so.2
libtheoraenc.so.1
I just did that to solve it:
`
sudo apt install libvorbisenc2 libtheora0
`
Maybe you're interested to include that in the documentation.

**Comment by paucazou** [comment]
I must add that there is no more problem with the latest version of Raspberry Pi OS.

**Comment by cedricve** [comment]
Ok cool! @paucazou thanks for reporting. It works well now?
