### ISSUE TITLE
New structure

### ISSUE THREAD

**Issue by cedricve** [kerberos-io/documentation#3]
The structure of the documentation website needs to be updated. Any suggestions to optimize the structure (make it more user-friendly) are welcome. The idea is that it would be more obvious to find guidelines of how to install kerberos.io, an explanation of the different parts and it should also be easy to find popular "how-to's" e.g. save images to a USB storage device or NAS.

The original structure is available on the master branch (https://doc.kerberos.io) and is visible below:

- Getting started
- Requirements
- Installation
- Release notes
- FAQ
- License
- Web
 - Introduction
 - Installation
 - Contribute
 - Project structure
- Machinery
 - Introduction
 - Installation
 - Contribute
 - Project structure
 - Capture
 - Condition
 - Algorithm
 - Expositor
 - Heuristic
 - Output
 - Captures
    - USB camera
    - IP camera
    - Raspberry camera
 - Conditions
    - Time
    - Enabled
 - Algorithms
    - Differential images
 - Expositors
    - Rectangle
    - Hull
 - Heuristics
    - Sequence
 - Outputs
    - Disk
    - TCP client
    - GPIO
    - Webhook
- Addons
  - TCP Listener
  - Cloud
  - NAS

Any help for restructuring topics, adding new headings or levels are welcome.

Thanks all! :)

**Comment by mishle** [comment]
- Download
    - SD Image
