### ISSUE TITLE
Camera List?

### ISSUE THREAD

**Issue by coltonhurst** [kerberos-io/documentation#40]
Hello!

Thank you for working on such a great project. I am looking into using Kerberos for a new security system. However, as someone new to the OSS Security System niche, I don't see any recommended cameras in the documentation. It seems like recommendations were going to be added in various locations, but there are no links (example: see [the USB camera section](https://doc.kerberos.io/opensource/machinery/#usb-camera), specifically this sentence: `You will find a complete list here.` that has no links. Maybe this is something that can be added, especially for people new to this space?

Additionally, it would be great to point out cameras that are supported, and also ones that do not send video feeds or any data back to the manufacturer. A random example - the Reolink camera might be a nice IP camera, but it probably sends data back to Reolink. Using a camera like this seems directly against the ideals of someone trying to set up an OSS security system in the first place.

I've exchanged emails with @cedricve and they recommended opening an issue and working together on this with the community 😊 Thank you again for working on such great software!

**Comment by cedricve** [comment]
As mentioned above this has been moved to a separate issue (https://github.com/kerberos-io/agent/issues/59). Special thanks to @coltonhurst  for initiating this idea!!
